image: node:7

before_script:
  - npm prune
  - npm update -q

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - NODE_ENV=ci npm run test
    
deploy_staging:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/duo2-backend-staging.git
    - git push heroku master
    - echo "Deployed to staging server"
  only:
    - master