image: node:10.17.0-alpine

cache:
  key: 'alpine'
  paths:
    - node_modules/

stages:
  - test
  - build
  - e2etest
  - autodeploy

test:
  stage: test
  script:
    - rm -rf node_modules && rm -rf package-lock.json && npm install
    - NODE_ENV=ci npm run test
  tags:
    - docker

docker build:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker build . -t dmsc/duo-frontend
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push dmsc/duo-frontend
  tags:
    - docker

e2etest:
  image: tiangolo/docker-with-compose
  stage: e2etest
  script:
    - apk add git
    - rm -rf duo-backend
    - git clone https://gitlab.esss.lu.se/swap/duo-backend.git
    - docker-compose -f docker-compose.e2e.yaml rm
    - docker-compose -f docker-compose.e2e.yaml down --remove-orphans
    - docker-compose -f docker-compose.e2e.yaml pull
    - docker-compose -f docker-compose.e2e.yaml build
    - docker-compose -f docker-compose.e2e.yaml up --exit-code-from cypress
    - docker-compose -f docker-compose.e2e.yaml down
  tags:
    - docker

autodeploy:
  image: ubuntu:latest
  stage: autodeploy
  script:
    - echo $CI_COMMIT_SHA
    - apt-get update -qq
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_GEN")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - until ssh jekabskarklins@scicat09.esss.lu.se "/home/jekabskarklins/duo-kubernetes/frontend/autodeploy.sh dev"; do sleep 5 ; done
  tags:
    - dind
  only:
    - develop
