image: node:8.10.0-alpine
cache:
  key: "alpine"
  paths:
    - node_modules/

stages:
  - test
  - build
  - production

build:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - npm install
    - npm run build
  tags:
    - docker
  only:
    - master

test:
  stage: test
  script:
    - npm install
    - NODE_ENV=ci npm run test
  tags:
    - docker




production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=duo2-frontend-staging --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - master
  tags:
    - docker