image: node:8.10.0-alpine

variables:
  REGISTRY_URL: https://artifactory.esss.lu.se/artifactory/api/npm/swap-npm/

cache:
  key: "alpine"
  paths:
    - node_modules/

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm config set @swap:registry $REGISTRY_URL
    - npm install
    - NODE_ENV=ci npm run test
  tags:
    - docker

docker build:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker build . -t dmsc/duo-frontend
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push dmsc/duo-frontend
  tags:
    - docker
  only:
    - master
