image: node:7

variables:
  REGISTRY_URL: https://$SWAP_NPM_REGISTRY_HOST/$SWAP_NPM_REGISTRY_PATH

stages:
  - test
  - build-test
  - build

test:
  stage: test
  script:
    - npm config set @swap:registry $REGISTRY_URL
    - npm install
    - NODE_ENV=ci npm run test
  tags:
    - docker

build-test:
  stage: build-test
  script:
    - npm config set @swap:registry $REGISTRY_URL
    - npm install --only=production
    - npm run tsc
  tags:
    - docker
  except:
    - master

docker build:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker build . -t dmsc/duo-backend
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push dmsc/duo-backend
  tags:
    - docker
  only:
    - master
