image: node:7

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm install
    - NODE_ENV=ci npm run test
  tags:
    - docker

docker build:
  image: docker:stable
  stage: build
  script:
  - docker info
  - docker build . -t dmsc/duo-backend
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push dmsc/duo-backend
  tags:
    - docker
  only:
    - master