image: node:7

before_script:
  - npm prune
  - npm update -q

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - NODE_ENV=ci npm run test
    
deploy_staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=duo2-backend-staging --api-key=$HEROKU_API_KEY
  only:
    - master
    