image: node:8.10.0-alpine
cache:
  key: "alpine"
  paths:
    - node_modules/

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm prune
    - npm update -q
    - NODE_ENV=ci npm run test
  tags:
    - docker

docker build:
  image: docker:stable
  stage: build
  script:
  - docker info
  - docker build . -t dmsc/duo-frontend
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push dmsc/duo-frontend
  tags:
    - docker
