name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        env:
          BUILD_VERSION: ${{ github.sha }}
        run: |
          cd ./apps/user-office-backend
          docker build -t user-office-backend:${{ github.sha }} .
          docker tag user-office-backend:${{ github.sha }} ghcr.io/userofficeproject/user-office-backend:${{ steps.tag_version.outputs.new_tag }}
          docker push ghcr.io/userofficeproject/user-office-backend:${{ steps.tag_version.outputs.new_tag }}

      - name: Build and push frontend
        env:
          BUILD_VERSION: ${{ github.sha }}
          ORCID_REDIRECT: ${{ secrets.REACT_APP_ORCID_REDIRECT }}
        run: |
          cd ./apps/user-office-frontend
          docker build -t user-office-frontend:${{ github.sha }} .
          docker tag user-office-frontend:${{ github.sha }} ghcr.io/userofficeproject/user-office-frontend:${{ steps.tag_version.outputs.new_tag }}
          docker push ghcr.io/userofficeproject/user-office-frontend:${{ steps.tag_version.outputs.new_tag }}
