name: Build && Push

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: |
          # Extract tag name
          TAG_NAME=${{ github.event.release.tag_name }}

          # set output variable accessible in the action
          echo ::set-output name=TAG_NAME::${TAG_NAME}

      - name: Build and push backend
        env:
          BUILD_VERSION: ${{ github.sha }}
        run: |
          cd ./apps/user-office-backend
          docker build -t user-office-backend:${{ github.sha }} .
          docker tag user-office-backend:${{ github.sha }} ghcr.io/userofficeproject/user-office-backend:${{ steps.extract_tag.outputs.TAG_NAME }}
          docker push ghcr.io/userofficeproject/user-office-backend:${{ steps.extract_tag.outputs.TAG_NAME }}

      - name: Build and push frontend
        env:
          BUILD_VERSION: ${{ github.sha }}
          ORCID_REDIRECT: ${{ secrets.REACT_APP_ORCID_REDIRECT }}
        run: |
          cd ./apps/user-office-frontend
          docker build -t user-office-frontend:${{ github.sha }} .
          docker tag user-office-frontend:${{ github.sha }} ghcr.io/userofficeproject/user-office-frontend:${{ steps.extract_tag.outputs.TAG_NAME }}
          docker push ghcr.io/userofficeproject/user-office-frontend:${{ steps.extract_tag.outputs.TAG_NAME }}
