# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test && Build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Use action to run end to end
      uses: UserOfficeProject/user-office-e2e-testing-action@v8
    - run: docker-compose -f docker-compose.e2e.yaml up --exit-code-from cypress
    - run: apk add git
    - run: rm -rf duo-backend
    - run: git clone https://gitlab.esss.lu.se/swap/duo-backend.git
    - run: docker-compose -f docker-compose.e2e.yaml rm
    - run: docker-compose -f docker-compose.e2e.yaml down --remove-orphans
    - run: docker-compose -f docker-compose.e2e.yaml pull
    - run: docker-compose -f docker-compose.e2e.yaml build
    - run: docker-compose -f docker-compose.e2e.yaml down
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: dmsc/duo-frontend
        tag_with_ref: true
